### ISSUE TITLE
Is mlet supposed to be used with different monads in the same time?

### ISSUE THREAD

**Issue by serioga** [funcool/cats#150]
The initial idea was to mix `maybe` and `exception` (I've created my custom exception with MonadPlus/MonadZero). But I found the results unpredictable.

```clojure
(m/mlet [b (either/right "b")
         a (maybe/just "a")
         :when (= a "b")]
  (m/return a))
=> #<Just "a"> ; expect Nothing

(m/mlet [a (maybe/just "a")
         b (either/right "b")
         :when (= a "b")]
  (m/return a))
=> #<Nothing> ; OK

(m/mlet [b (either/right "b")
         a (maybe/just "a")
         :when (= a "b")]
  (m/return b))
=> #<Just "a"> ; "a"? Expect nothing anyway
```

**Comment by yurrriq** [comment]
Short answer: probably not.

-----

```clj
(macroexpand '(m/mlet [b (either/right "b")
                       a (maybe/just "a")
                       :when (= a "b")]
                (m/return a)))
```

Cleaned up for legibility...
```clj

(m/bind (either/right "b")
  (fn [b] (m/bind (maybe/just "a")
           (fn [a] (m/bind (m/guard (= a "b"))
                    (fn [_] (do (m/return a))))))))
```

With some helpful `println`s.
```clj
(m/bind (either/right "b")
  (fn [b]
    (println "b." (context/get-current))
    (m/bind (maybe/just "a")
      (fn [a]
        (println "a." (context/get-current))
        (m/bind (m/guard (= a "b"))
          (fn [_] (do (m/return a))))))))
```
```
b. #<Either>
#<Just "a">
```

Either's `-mbind` is defined as follows:
```clj
(-mbind [_ s f]
  (if (right? s)
    (f (.-v s))
    s))
```

Since we're in the Either context after the first bind, we're effectively calling:
```clj
(-mbind either/context (maybe/just "a") (fn [a] ...))
```

And since `right?` doesn't hold for `#<Just "a">`, `-mbind` returns `#<Just "a">`.

**Comment by yurrriq** [comment]
re: second example

Maybe's `-mbind` is defined:
```clj
(-mbind [_ mv f]
  (if (nothing? mv)
    mv
    (f (p/-extract mv))))
```

So when you effectively try to `(-mbind maybe/context (either/right? "b") f)`, `(nothing? (either/right? "b"))` doesn't hold, so we extract `"b"` and call `(f "b")`.

`f` then tries to `(m/bind (m/guard (= "a" "b")) ...)` and since `(= "a" "b")` doesn't hold, `m/guard` calls `(mzero maybe/context)`, thus the `#<Nothing>`.

**Comment by yurrriq** [comment]
@dialelo, @niwinz: Should we be more strict about contexts in `-mbind` implementations? It seems like this is perhaps unnecessarily confusing. If we were to assert the proper context, these sorts of examples could fail earlier and more obviously..

**Comment by niwinz** [comment]
@yurrriq seems like a plan. In any case we have a plan for rewrite how the context is managed covered in #140. That will be more strict and will not allow mix things.

In any case we should not wait for #140 so we can add proper checks today to the current impl.

**Comment by dialelo** [comment]
Agree about only allowing one context :+1: #140 may take some time to land so we shouldn't wait.

**Comment by serioga** [comment]
Clear, thank you.
