### ISSUE TITLE
Is there a reason Exception and Maybe don't implement Bifunctor?

### ISSUE THREAD

**Issue by mattly** [funcool/cats#170]
Perhaps I'm misunderstanding Monadic laws or the like, but I've hit a situation where it would be useful to `bimap` over an Exception or Maybe monad without necessarily knowing which type it is, and it seems only Either implements the Bifunctor protocol. Is this for Category Theory reasons or simply an omission?

**Comment by yurrriq** [comment]
I wasn't able to find any good resources online quickly, but as I understand it, a `Bifunctor` instance for `Exception` or `Maybe` doesn't make sense, because unlike `Either` or `Pair`, there's no "left" value to map over.

`Nothing` represents the absence of a value and `Exception` represents an error, thus not a desirable value. Therefore it doesn't make sense to want to map over them.

**Comment by yurrriq** [comment]
If you look at [`Data.Bifunctor`](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Bifunctor.html):

```haskell
Bifunctor Either
Bifunctor (,)
Bifunctor Const
Bifunctor ((,,) x1)
Bifunctor ((,,,) x1 x2)
Bifunctor ((,,,,) x1 x2 x3)
Bifunctor ((,,,,,) x1 x2 x3 x4)
Bifunctor ((,,,,,,) x1 x2 x3 x4 x5)
```

We've got instances for `cats.data.Pair` and `cats`monad.Either`, but maybe it'd be cool to do `clojure.lang.PersistenVector` or some other `seq`s too.

**Comment by niwinz** [comment]
I agree with @yurrriq
